# Подготовка территорий

Используем класс `LandDataPreparator`, чтобы собрать единый набор данных и сохранить результат.

### Входные данные

**scenario_blocks_path = "../data/prostor/scenario_blocks.pickle"** — GeoDataFrame сценарных участков. Обязательные атрибуты: геометрия `geometry` (проекция в метрах), доли типов использования (`residential`, `business`, `recreation`, `industrial`, `transport`, `special`, `agriculture`), агрегированные показатели `land_use`, `share`, `footprint_area`, `build_floor_area`, `living_area`, `non_living_area`.

**context_blocks_path = "../data/prostor/context_blocks.pickle"** — GeoDataFrame контекстных участков с идентичной структурой и той же CRS; используется для объединения с сценарными блоками.

**accessibility_matrix_path = "../data/prostor/acc_mx.pickle"** — DataFrame с матрицей доступности, индекс которой синхронизирован с блоками, и обязательным набором показателей доступности (например `area_accessibility` и связанные метрики), которые функция `area_accessibility` переносит в итоговый GeoDataFrame.

In [1]:
import pandas as pd
from urbanomy.methods.land_value_modeling.land_data_preparation import LandDataPreparator

In [2]:
scenario_blocks = pd.read_pickle('../data/scenario_blocks.pickle')
context_blocks = pd.read_pickle('../data/context_blocks.pickle')
accessibility_matrix = pd.read_pickle('../data/acc_mx.pickle')

preparator = LandDataPreparator(
    scenario_blocks_source=scenario_blocks,
    context_blocks_source=context_blocks,
    accessibility_matrix_source=accessibility_matrix,
)

In [5]:
scenario_blocks

,geometry,residential,business,recreation,industrial,transport,special,agriculture,land_use,share
0,"POLYGON ((388511.373 6644951.946, 388558.037 6...",0.000000,0.000000,0.0,0.0,0.000000,0.0,0.91818,LandUse.AGRICULTURE,0.918180
1,"POLYGON ((388558.037 6645102.374, 388511.373 6...",0.000000,0.938081,0.0,0.0,0.000000,0.0,0.00000,LandUse.BUSINESS,0.938081
2,"POLYGON ((387957.434 6643444.937, 388007.492 6...",0.000000,0.000000,0.0,0.0,0.891381,0.0,0.00000,LandUse.TRANSPORT,0.891381
3,"POLYGON ((388007.492 6643608.409, 387957.434 6...",0.934862,0.000000,0.0,0.0,0.000000,0.0,0.00000,LandUse.RESIDENTIAL,0.934862
4,"POLYGON ((388001.306 6643195.969, 388000.75 66...",0.000000,0.000000,0.0,0.0,0.000000,0.0,0.00000,None,NaN
...,...,...,...,...,...,...,...,...,...,...
65,"POLYGON ((390950.379 6643779.96, 390941.389 66...",0.000000,1.000000,0.0,0.0,0.000000,0.0,0.00000,LandUse.BUSINESS,1.000000
66,"POLYGON ((391069.678 6644283.933, 391072.529 6...",0.000000,0.000000,0.0,0.0,0.000000,0.0,1.00000,LandUse.AGRICULTURE,1.000000
67,"POLYGON ((388222.552 6643218.262, 388215.418 6...",0.000000,0.000000,0.0,0.0,0.910136,0.0,0.00000,LandUse.TRANSPORT,0.910136
68,"POLYGON ((388314.421 6645193.77, 388311.871 66...",0.000000,1.000000,0.0,0.0,0.000000,0.0,0.00000,LandUse.BUSINESS,1.000000
69,"POLYGON ((390404.263 6642900.867, 390408.695 6...",0.000000,0.000000,0.0,0.0,0.000000,1.0,0.00000,LandUse.SPECIAL,1.000000

In [3]:
prepared_blocks = preparator.prepare()
prepared_blocks.head()

2025-10-14 12:24:30.249 | WARNING  | blocksnet.analysis.morphotypes.schemas:_before_validate:17 - Column l not found in columns. Calculating from fsi and gsi

,residential,business,recreation,industrial,transport,special,agriculture,land_use,share,footprint_area,...,site_area,fsi,gsi,mxi,l,morphotype,area_accessibility,is_scn,geometry,id
0,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.91818,LandUse.AGRICULTURE,0.918180,6260.339339,...,202399.732193,0.062008,0.030931,0.000000,2.004749,low-rise non-residential,83.073985,True,"POLYGON ((388511.373 6644951.946, 388558.037 6...",0
1,0.000000,0.938081,0.0,0.0,0.000000,0.0,0.00000,LandUse.BUSINESS,0.938081,18143.803825,...,201529.493481,0.202340,0.090031,0.000000,2.247463,low-rise non-residential,82.652504,True,"POLYGON ((388558.037 6645102.374, 388511.373 6...",1
2,0.000000,0.000000,0.0,0.0,0.891381,0.0,0.00000,LandUse.TRANSPORT,0.891381,15011.639457,...,164663.859830,0.151737,0.091165,0.000000,1.664418,low-rise non-residential,109.288479,True,"POLYGON ((387957.434 6643444.937, 388007.492 6...",2
3,0.934862,0.000000,0.0,0.0,0.000000,0.0,0.00000,LandUse.RESIDENTIAL,0.934862,22467.050757,...,161571.832511,0.449142,0.139053,0.404539,3.230005,low-rise model,112.015000,True,"POLYGON ((388007.492 6643608.409, 387957.434 6...",3
4,0.000000,0.000000,0.0,0.0,0.000000,0.0,0.00000,None,NaN,0.316008,...,16.489152,0.079224,0.019165,0.000000,4.133894,mid-rise non-residential,82.790797,True,"POLYGON ((388001.306 6643195.969, 388000.75 66...",4

In [4]:
prepared_blocks.to_pickle("../data/prepared_blocks.pickle")