In [1]:
import pandas as pd
import geopandas as gpd
from typing import Final
from blocksnet.enums import LandUse

In [2]:
basline_blocks = gpd.read_file('../data/gatchina/blocks_clean_gatchina.geojson')

basline_blocks["is_project"] = False
basline_blocks.loc[basline_blocks.iloc[7].name, "is_project"] = True

In [3]:
basline_blocks.iloc[7]

residential                                                           0.0
business                                                              0.0
recreation                                                            0.0
industrial                                                       0.727595
transport                                                        0.000757
special                                                          0.200502
agriculture                                                           0.0
land_use                                               LandUse.INDUSTRIAL
share                                                            0.727595
footprint_area                                                3990.876381
build_floor_area                                              3990.876381
living_area                                                           0.0
non_living_area                                               3990.876381
population                                                            0.0
fsi                                                              0.003099
gsi                                                              0.003099
mxi                                                                   0.0
l                                                                     1.0
morphotype                                       low-rise non-residential
area_accessibility                                               15.79344
site_area                                                   330924.593388
land_value                                               195468342.222565
land_value_per_100m2                                         59067.336223
id                                                                      7
geometry                POLYGON ((30.1513298 59.5866794, 30.1507783 59...
is_project                                                           True
Name: 7, dtype: object

In [4]:
from urbanomy.methods.investment_potential import prepare_investment_input

investment_input = prepare_investment_input(
    gdf = basline_blocks
)

investment_input.head()

2026-03-05 15:35:46.638 | WARNING  | urbanomy.utils.investment_input:prepare_investment_input:265 - prepare_investment_input: колонка 'land_value_before' не найдена; значения скопированы из 'land_value'.

,land_use,land_value,land_value_before,residential,business,recreation,industrial,transport,special,agriculture,site_area,living_area,non_living_area,build_floor_area,share
0,LandUse.INDUSTRIAL,1.954683e+08,1.954683e+08,0.0,0.0,0.0,240779.026282,250.628307,66351.017685,0.0,330924.593388,0.0,3990.876381,3990.876381,0.727595

## Инвевстиционная привлекательность

In [ ]:
from blocksnet.enums import LandUse

benchmarks_demo = {
    LandUse.RESIDENTIAL: {
        "cost_build": 45_000,
        "price_sale": 140_000,
        "construction_years": 3,
        "sale_years": 4,
        "opex_rate": 800,
        "cost_demolition": 900,  # ₽/м² ориентировочно по России
    },
    LandUse.BUSINESS: {
        "cost_build": 55_000,
        "rent_annual": 25_000,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 1_300,
        "cost_demolition": 900,
    },
    LandUse.RECREATION: {
        "cost_build": 20_000,
        "rent_annual": 7_500,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 1_000,
        "cost_demolition": 900,
    },
    LandUse.SPECIAL: {
        "cost_build": 35_000,
        "rent_annual": 11_000,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 1_500,
        "cost_demolition": 900,
    },
    LandUse.INDUSTRIAL: {
        "cost_build": 38_000,
        "rent_annual": 14_800,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 700,
        "cost_demolition": 900,
    },
    LandUse.AGRICULTURE: {
        "cost_build": 25_000,
        "rent_annual": 6_500,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 300,
        "cost_demolition": 900,
    },
    LandUse.TRANSPORT: {
        "cost_build": 18_000,
        "rent_annual": 8_200,
        "rent_years": 15,
        "construction_years": 3,
        "opex_rate": 600,
        "cost_demolition": 900,
    },
}

In [6]:
from urbanomy.methods.investment_potential import InvestmentAttractivenessAnalyzer

an = InvestmentAttractivenessAnalyzer(benchmarks=benchmarks_demo)
summary = an.calculate_investment_metrics(investment_input, discount_rate=0.18)
summary

Project totals:
 • Land area:          307,380.67
 • Built area:         3,990.88
 • Land value:         195,468,342.22
 • Demolition cost:    3,591,788.74
 • Construction cost:  149,003,816.89
 • Investment need:    348,063,947.86
 • Project NPV:        -187,251,910.23
 • Project IRR:        0.05
 • Project ROI:        1.86
 • Project PI:         0.42
 • Project PP (yrs):   nan

,land_use,land_area,land_value_before,built_area,land_value,demolition_cost,construction_cost,investment_need,NPV,IRR,ROI,PI,PP_years,EI
0,LandUse.INDUSTRIAL,307380.67,1.954683e+08,3990.88,1.954683e+08,3591788.74,1.490038e+08,3.480639e+08,-1.872519e+08,0.05,1.86,0.42,NaN,0.0

In [7]:
# scn.to_file('../data/blocks_investment.geojson', driver='GeoJSON')