In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
gdf = gpd.read_file('../data/blocks_investment.geojson')
gdf.head()

,land_use,land_area,land_value_before,built_area,land_value,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry
0,LandUse.AGRICULTURE,202399.73,1.040179e+08,12550.41,1.889022e+08,3.137603e+08,5.026624e+08,-1.971050e+08,0.09,2.92,NaN,0.00,3.0,45.00,"POLYGON ((388511.373 6644951.946, 388558.037 6..."
1,LandUse.BUSINESS,201529.49,1.035707e+08,40777.54,2.096246e+08,2.242764e+09,2.452389e+09,1.175440e+09,0.27,12.59,8.41,87.85,2.0,76.50,"POLYGON ((388558.037 6645102.374, 388511.373 6..."
2,LandUse.TRANSPORT,164663.86,8.462455e+07,24985.65,1.502461e+08,4.497417e+08,5.999878e+08,7.812487e+07,0.21,7.38,12.73,29.17,4.0,53.96,"POLYGON ((387957.434 6643444.937, 388007.492 6..."
3,LandUse.RESIDENTIAL,161571.83,8.303549e+07,72568.69,4.697694e+08,3.265591e+09,3.735361e+09,1.532286e+09,0.32,4.97,5.44,100.00,0.0,60.00,"POLYGON ((388007.492 6643608.409, 387957.434 6..."
4,None,NaN,3.494860e+03,NaN,4.721626e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"POLYGON ((388001.306 6643195.969, 388000.75 66..."

In [ ]:
from urbanomy.methods.socio_economic_indicators.constants import (
    DEFAULT_VA_PER_M2_OPS,
    DEFAULT_JOBS_PER_M2,
    DEFAULT_WAGE_BY_USE,
    DEFAULT_PROFIT_SHARE_OPS,
    DEFAULT_CAPEX_CAPITALIZABLE_SHARE,
    DEFAULT_AMORTIZATION_RATES,
)

project_cfg = {
    "population": 600_000,  # Население базовой территорииА
    "construction_period_years": 3,  # Срок строительства в годах
    "employment_share": 0.62,  # Доля занятых (по умолчанию 0.62)
    "avg_wage_base": 74_000,  # Средняя зарплата до проекта
    "build_wage_share": 0.27,  # Доля зарплаты в инвестициях на стройке
    "build_profit_margin": 0.065,  # Рентабельность строительства
    "tax_rates": {  # Налоговые ставки проекта
        "pit": 0.12,  # НДФЛ
        "cit": 0.17,  # налог на прибыль
        "prop": 0.025,  # налог на имущество
        "land": 0.015,  # земельный налог
    },
    "va_coeff_build": {  # Коэффициенты валовой добавленной стоимости на стройке
        "default": 0.50,  # базовый коэффициент для прочих категорий
        "business": 0.55,  # повышаем мультипликатор для деловой застройки
        "special": 0.52,  
    },
    "va_per_m2_ops": {  # ВДС на квадратный метр в эксплуатации
        **DEFAULT_VA_PER_M2_OPS,
        "business": 13_500.0,  
        "transport": 5_500.0,  
    },
    "jobs_per_m2": {  # Рабочие места на квадратный метр
        **DEFAULT_JOBS_PER_M2,
        "business": 1 / 20, 
        "special": 1 / 28, 
    },
    "wage_by_use": {  # Средние зарплаты по видам использования земли
        **DEFAULT_WAGE_BY_USE,
        "business": 92_000, 
        "transport": 63_000,  
    },
    "profit_share_ops": {  # Доли прибыли в обороте в эксплуатации
        **DEFAULT_PROFIT_SHARE_OPS,
        "business": 0.20, 
        "special": 0.16,  
    },
    "capex_capitalizable_share": {  # Доля капзатрат, переходящих в основные средства
        **DEFAULT_CAPEX_CAPITALIZABLE_SHARE,
        "transport": 0.92,  
    },
    "amortization_rates": {  # Годовые нормы амортизации
        **DEFAULT_AMORTIZATION_RATES,
        "business": 0.032,  
        "special": 0.045,  
}}

In [5]:
from urbanomy.methods.socio_economic_indicators.sei_calculate import SEREstimator

deafaut_cfg = {
    "population": 300_000,
}

est = SEREstimator(project_cfg) # or use project_cfg
result = est.compute(gdf, pretty=True)
result

                                           indicator    delta_total
0  Объём инвестиций в основной капитал на душу на...         90 274
1     Валовый региональный продукт на душу населения         55 650
2                          Доходы бюджета территории  6 596 931 840
3                   Средний уровень заработной платы            416
4                  Износ основного фонда (тыс. руб.)      1 833 046