In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd

In [2]:
df = gpd.read_file('./data/prostor/blocks_investment.geojson')
df

DataSourceError: ./data/prostor/blocks_investment.geojson: No such file or directory

In [ ]:
import numpy as np

land_cost = pd.to_numeric(df['land_cost'], errors='coerce')
rng = np.random.default_rng(42)
df['land_cost_before'] = (land_cost * (0.93 - 0.05 * rng.random(len(df)))).round(2)
df

,land_use,land_area,built_area,land_cost,construction_cost,investment_need,NPV,IRR,ROI,PP_years,EI,spatial_potential,INV,geometry,land_cost_before
0,AGRICULTURE,202399.73,12550.42,8.195883e+07,3.137604e+08,3.957192e+08,-2.266165e+08,0.00,0.92,NaN,0.00,3.0,21.36,"POLYGON ((388511.373 6644951.946, 388558.037 6...",7.305008e+07
1,BUSINESS,201529.49,40777.55,1.457553e+08,2.242765e+09,2.388521e+09,2.259647e+08,0.14,4.81,12.87,45.55,2.0,26.09,"POLYGON ((388558.037 6645102.374, 388511.373 6...",1.323540e+08
2,TRANSPORT,164663.86,24985.66,7.927197e+07,4.497418e+08,5.290138e+08,-5.605498e+07,0.10,3.83,NaN,0.00,4.0,42.73,"POLYGON ((387957.434 6643444.937, 388007.492 6...",7.031980e+07
3,RESIDENTIAL,161571.83,72568.71,2.486372e+08,3.265592e+09,3.514229e+09,1.204906e+09,0.27,2.51,4.11,91.47,4.0,95.11,"POLYGON ((388007.492 6643608.409, 387957.434 6...",2.225630e+08
4,RESIDENTIAL,49.93,2.17,7.532216e+04,9.764970e+04,1.729719e+05,-3.185744e+04,0.04,1.14,NaN,0.00,4.0,42.73,"POLYGON ((388000.75 6643199.606, 388001.306 66...",6.969493e+04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62,BUSINESS,606.98,203.64,5.072911e+05,1.120007e+07,1.170736e+07,2.220737e+06,0.16,5.56,11.41,10.36,2.0,5.94,"POLYGON ((390950.379 6643779.96, 390941.389 66...",4.574438e+05
63,AGRICULTURE,2.67,NaN,1.102000e+01,NaN,1.102000e+01,-2.750999e+04,0.03,1.64,NaN,0.00,3.0,21.36,"POLYGON ((391069.678 6644283.933, 391072.529 6...",9.830000e+00
64,TRANSPORT,4307.66,688.58,2.103883e+06,1.239436e+07,1.449824e+07,-1.169555e+06,0.11,4.01,NaN,0.00,4.0,42.73,"POLYGON ((388222.552 6643218.262, 388215.418 6...",1.889842e+06
65,BUSINESS,61.63,13.49,5.911855e+04,7.418000e+05,8.009186e+05,1.215635e+05,0.15,5.09,11.93,7.90,2.0,4.52,"POLYGON ((388314.421 6645193.77, 388311.871 66...",5.334391e+04
66,SPECIAL,175.85,60.89,7.550822e+04,2.131233e+06,2.206741e+06,1.624798e+05,0.13,5.75,15.44,3.55,4.0,44.76,"POLYGON ((390404.263 6642900.867, 390408.695 6...",6.811141e+04

In [ ]:
from urbanomy.methods.ser.ser_calculate import SEREstimator

est = SEREstimator({
    'population': 500_000,
    'employment_base': 230_000,
})
result = est.compute(df, pretty=True)
result

,indicator,delta_build_year,delta_ops_year
0,Объём инвестиций в основной капитал на душу на...,116 189,
1,Валовый региональный продукт на душу населения,18 535,12 789
2,Доходы бюджета территории,7 716 868 005,4 168 445 716
3,Средний уровень заработной платы,,807
4,Износ основного фонда (тыс. руб.),,1 878 673